# -*- coding: utf-8 -*-
"""Voice via GOOGLE TTS (Chirp3 HD) for path B + estimated word timing for karaoke.

Google TTS returns NO word boundaries, so per-word timing is ESTIMATED: the speech
window (duration - head - tail) is distributed by each word's syllable weight, plus
pauses after punctuation (same weighted distribution as path A's subtitles.py).
Real-world error ~100-200ms, smooth enough for karaoke.

Use when the user wants a Google voice (e.g. Chirp3-HD-Charon, northern male).
"""
import argparse
import json
import re
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_voice import merge_phonetics  # noqa: E402

from lib.tts.google_tts import synthesize_sync  # noqa: E402  (pip install -e any2video)

HERE = Path(__file__).resolve().parent.parent

VOWELS = re.compile(
    r"[aeiouyăâêôơưàảãáạằẳẵắặầẩẫấậèẻẽéẹềểễếệìỉĩíịòỏõóọồổỗốộờởỡớợùủũúụừửữứựỳỷỹýỵ]+",
    re.IGNORECASE,
)


def syllables(word: str) -> int:
    return max(1, len(VOWELS.findall(word)))


def estimate_words(text: str, duration: float, head=0.12, tail=0.25):
    tokens = text.split()
    weights = []
    for t in tokens:
        w = float(syllables(t.strip(".,?!")))
        if t.endswith((".", "?", "!")):
            w += 1.1  # sentence pause
        elif t.endswith(","):
            w += 0.45  # comma pause
        weights.append(w)
    window = max(0.5, duration - head - tail)
    total = sum(weights)
    words = []
    cur = head
    for t, w in zip(tokens, weights):
        pause = 1.1 if t.endswith((".", "?", "!")) else (0.45 if t.endswith(",") else 0.0)
        speak = (w - pause) / total * window
        gap = pause / total * window
        words.append({"w": t, "s": round(cur, 3), "e": round(cur + speak, 3)})
        cur += speak + gap
    return words


def audio_dur(p: Path) -> float:
    r = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", str(p)], capture_output=True, text=True)
    return float(r.stdout.strip())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scenes", required=True)
    ap.add_argument("--prefix", required=True)
    ap.add_argument("--data-out", required=True)
    ap.add_argument("--audio-dir", default=str(HERE / "public" / "audio"))
    ap.add_argument("--voice", default="vi-VN-Chirp3-HD-Charon")
    ap.add_argument("--rate", default="+5%", help="skill standard for Chirp3")
    ap.add_argument("--lang", default="vi")
    ap.add_argument("--fps", type=int, default=30)
    ap.add_argument("--pad", type=float, default=0.8)
    ap.add_argument("--min-frames", type=int, default=100)
    args = ap.parse_args()

    scenes = json.loads(Path(args.scenes).read_text(encoding="utf-8"))
    audio_dir = Path(args.audio_dir)
    audio_dir.mkdir(parents=True, exist_ok=True)

    out = []
    for sc in scenes:
        aud = audio_dir / f"{args.prefix}_{sc['id']}.mp3"
        r = synthesize_sync(sc["narration"], args.voice, aud, args.rate, args.lang)
        if not aud.exists() or aud.stat().st_size < 1000:
            raise RuntimeError(f"Google TTS fail scene {sc['id']}: {r}")
        time.sleep(0.2)
        dur = audio_dur(aud)
        words = merge_phonetics(estimate_words(sc["narration"], dur))
        frames = max(args.min_frames, int((dur + args.pad) * args.fps))
        print(f"[{sc['id']}] {dur:.2f}s, {len(words)} words -> {frames} frames")
        out.append(dict(id=sc["id"], audio=f"audio/{args.prefix}_{sc['id']}.mp3",
                        durationInFrames=frames, words=words))

    total = sum(s["durationInFrames"] for s in out)
    ts = "// Generated by tools/gen_voice_google.py (ESTIMATED timing). Do not hand-edit.\n"
    ts += "import type { SceneTiming } from \"../lib/core\";\n\n"
    ts += "export const SCENES: SceneTiming[] = " + json.dumps(out, ensure_ascii=False, indent=2) + ";\n\n"
    ts += f"export const TOTAL_FRAMES = {total};\n"
    Path(args.data_out).write_text(ts, encoding="utf-8")
    print(f"TOTAL: {total} frames = {total / args.fps:.1f}s")


if __name__ == "__main__":
    sys.exit(main())
