# -*- coding: utf-8 -*-
"""Voice via VieNeu-TTS (local, free, CPU-friendly) for path B + estimated karaoke timing.

VieNeu (github.com/pnnbao97/VieNeu-TTS, Apache-2.0) is a Vietnamese-native TTS with
instant voice cloning. It returns NO word boundaries, so per-word timing is ESTIMATED
with the same syllable-weight distribution as the Google variant.

VieNeu reads BILINGUAL text: wrap English words in <en>...</en> and the model
switches to native English pronunciation (e.g. "dung <en>GitHub Actions</en> de deploy").
Prefer <en> tags over phonetic spellings for this engine. The tags are sent to the
TTS as-is but STRIPPED from the karaoke words, so captions show the clean spelling.

Setup: point --vieneu-dir (or the VIENEU_TTS_DIR env var) at your local VieNeu-TTS
checkout (the dir holding its pyproject/uv env). The heavy work runs inside that env
via `uv run --no-sync` (--no-sync so uv never uninstalls the CPU torch build).

Example:
  python tools/gen_voice_vieneu.py --scenes workspace/runs/<slug>/narration.json \
      --prefix <slug> --data-out src/videos/<slug>-data.ts --voice "Ngọc Lan"
"""
import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_voice import merge_phonetics  # noqa: E402
from gen_voice_google import audio_dur, estimate_words  # noqa: E402

HERE = Path(__file__).resolve().parent.parent  # render-remotion/
BRIDGE = Path(__file__).resolve().parent / "vieneu_bridge.py"
EN_TAG = re.compile(r"</?en>")


def strip_en(text: str) -> str:
    """Karaoke display text: drop the <en> markers, keep the words."""
    return EN_TAG.sub("", text)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scenes", required=True)
    ap.add_argument("--prefix", required=True)
    ap.add_argument("--data-out", required=True)
    ap.add_argument("--audio-dir", default=str(HERE / "public" / "audio"))
    ap.add_argument("--vieneu-dir", default=os.environ.get("VIENEU_TTS_DIR", ""),
                    help="VieNeu-TTS checkout dir (or set VIENEU_TTS_DIR)")
    ap.add_argument("--voice", default="", help="built-in voice name (empty = default Ngọc Lan)")
    ap.add_argument("--ref-audio", default="", help="3-8s wav for instant voice cloning")
    ap.add_argument("--style", default="tu_nhien", help="delivery style (tu_nhien, ke_chuyen, ...)")
    ap.add_argument("--temperature", type=float, default=0.8, help="sampling temperature")
    ap.add_argument("--fps", type=int, default=30)
    ap.add_argument("--pad", type=float, default=0.8)
    ap.add_argument("--min-frames", type=int, default=100)
    args = ap.parse_args()

    if not args.vieneu_dir or not Path(args.vieneu_dir).is_dir():
        sys.exit("Set --vieneu-dir or VIENEU_TTS_DIR to your VieNeu-TTS checkout.")

    scenes_path = Path(args.scenes).resolve()
    audio_dir = Path(args.audio_dir).resolve()
    ref = str(Path(args.ref_audio).resolve()) if args.ref_audio else ""

    cmd = ["uv", "run", "--no-sync", "python", str(BRIDGE),
           "--scenes", str(scenes_path), "--audio-dir", str(audio_dir),
           "--prefix", args.prefix,
           "--style", args.style, "--temperature", str(args.temperature)]
    if ref:
        cmd += ["--ref-audio", ref]
    elif args.voice:
        cmd += ["--voice", args.voice]
    r = subprocess.run(cmd, cwd=args.vieneu_dir)
    if r.returncode != 0:
        sys.exit(f"vieneu bridge failed ({r.returncode})")

    scenes = json.loads(scenes_path.read_text(encoding="utf-8"))
    out = []
    for sc in scenes:
        aud = audio_dir / f"{args.prefix}_{sc['id']}.wav"
        if not aud.exists() or aud.stat().st_size < 1000:
            sys.exit(f"missing/short audio for scene {sc['id']}: {aud}")
        dur = audio_dur(aud)
        words = merge_phonetics(estimate_words(strip_en(sc["narration"]), dur))
        frames = max(args.min_frames, int((dur + args.pad) * args.fps))
        print(f"[{sc['id']}] {dur:.2f}s, {len(words)} words -> {frames} frames")
        out.append(dict(id=sc["id"], audio=f"audio/{args.prefix}_{sc['id']}.wav",
                        durationInFrames=frames, words=words))

    total = sum(s["durationInFrames"] for s in out)
    ts = "// Generated by tools/gen_voice_vieneu.py (ESTIMATED timing). Do not hand-edit.\n"
    ts += "import type { SceneTiming } from \"../lib/core\";\n\n"
    ts += "export const SCENES: SceneTiming[] = " + json.dumps(out, ensure_ascii=False, indent=2) + ";\n\n"
    ts += f"export const TOTAL_FRAMES = {total};\n"
    Path(args.data_out).write_text(ts, encoding="utf-8")
    print(f"TOTAL: {total} frames = {total / args.fps:.1f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
